---
title: "Image Read-In"
author: "Sabir Meah"
date: "2022-12-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(jpeg)
```

```{r}
no_dementia <- array(NA, dim = c(3200, 128, 128))
for (i in 1:3200){
  no_dementia[i,,] <- readJPEG(paste0(getwd(), "/Data/Non_Demented/non_", i, ".jpg"))
}
```

```{r}
verymild_dementia <- array(NA, dim = c(2240, 128, 128))
for (i in 1:2240){
  verymild_dementia[i,,] <- readJPEG(paste0(getwd(), "/Data/Very_Mild_Demented/verymild_", i, ".jpg"))
}
```

```{r}
mild_dementia <- array(NA, dim = c(896, 128, 128))
for (i in 1:896){
  mild_dementia[i,,] <- readJPEG(paste0(getwd(), "/Data/Mild_Demented/mild_", i, ".jpg"))
}
```

```{r}
moderate_dementia <- array(NA, dim = c(64, 128, 128))
for (i in 1:64){
  moderate_dementia[i,,] <- readJPEG(paste0(getwd(), "/Data/Moderate_Demented/moderate_", i, ".jpg"))
}
```

```{r}
lenNoDem <- 3200
lenVeryMildDem <- 2240
lenMildDem <- 896
lenModDem <- 64
totalLen <- lenNoDem + lenVeryMildDem + lenMildDem + lenModDem

class <- c(rep("No Dementia", lenNoDem), 
           rep("Very Mild Dementia", lenVeryMildDem),
           rep("Mild Dementia", lenMildDem),
           rep("Moderate Dementia", lenModDem))
```

```{r}
#dementia_data <- list(no_dementia, verymild_dementia, mild_dementia, moderate_dementia)
dementia_data <- array(NA, dim = c(6400, 128, 128))
dementia_data[1:lenNoDem,,] <- no_dementia
dementia_data[3201:(lenNoDem + lenVeryMildDem),,] <- verymild_dementia
dementia_data[5441:(lenNoDem + lenVeryMildDem + lenMildDem),,] <- mild_dementia
dementia_data[6337:totalLen,,] <- moderate_dementia
```

```{r}
# Don't push this file GitHub does not like it
saveRDS(dementia_data, file = "processed_dementia_data.rds")
```

```{r}
saveRDS(class, file = "dementia_classes.rds")
```























